--- 
config: 
  name: cjdname
foo: bar
fortune: 
  messages: 
    - "People are naturally attracted to you."
    - "You learn from your mistakes... You will learn a lot today."
hello: world

workshop: 
  contentURL: "https://workshop-content.cfapps.io"
  title: "Pivotal Cloud Foundry Workshop"
  date: "October 25 & 26, 2016"
  description: "This workshop will cover the ..."
  customerLogo: "http://www.johnhancock.com/resources/images/common/john-hancock-logo.gif"
  instructors: 
    - 
      name: "Chris J. Decelles"
      title: "Sr. Platform Architect"
      email: cdecelles@pivotal.io
      phone: "603.512.5616"
  resources:
    -
      title: "Pivotal Network"
      url: "https://network.pivotal.io/"
    -
      title: "Pivotal Documentation"
      url: "http://docs.pivotal.io/"
    -
      title: "cf CLI Documentation"
      url: "https://docs.pivotal.io/pivotalcf/cf-cli/getting-started.html"
    -
      title: "Manifest Documentation"
      url: "https://docs.pivotal.io/pivotalcf/devguide/deploy-apps/manifest.html"
    -
      title: "Spring Documentation"
      url: "https://spring.io/docs"
    -
      title: "Spring Initializr"
      url: "http://start.spring.io/"
    -
      title: "Pivotal Web Services"
      url: "https://run.pivotal.io/"
  requirements:
    -
      title: "Test"
      requirement:
        -
          content: "content 1 link"
        -
          content: "content 2 link"
    -
      title: "CLI"
      requirement:
      -
        content: "content 3 link"
      -
        content: "content 4 link"
  sessions:
    - 
      id: "day1"
      name: "Day 1"
      description: "Content for October, 25"
      topics:
      -
        id: "session1"
        title: "Application Development"
      -
        id: "04-cli"
      -
        id: "08-deploy-simple-app"
      -
        id: "06-org-space-user-role"
      -
        id: "10-application-manifest"
      -
        id: "12-domains-and-routes"
      -
        id: "14-services"
      -
        id: "20a-opsmgr-and-bosh-short"
      -
        id: "26-elastic-runtime"
      -
        id: "40-high-availability"
      -
        id: "session1"
        title: "Customization"
      -
        id: "56-cloud-controller-API"
      -
        id: "58-service-broker"
      -
        id: "59-oauth-primer"
      -
        id: "60-security-and-sso"
      -
        id: "62-buildpacks"
      -
        id: "session3"
        title: "Cloud Native Apps and Continuous Delivery"
      -
        id: "why-cloud-native-slides"
      -
        id: "cna-culture-changes-slides"
      -
        id: "66-continuous-delivery"
      -
        id: "68-cloud-native-design"
      -
        id: "70-microservices"
    - 
      id: "day2"
      name: "Day 2"
      description: "Content for October, 26"
      topics:
      -
        id: "springboot"
        title: "Spring Boot"
      -
        id: "spring-boot-labs-setup"
      -
        id: "80-cs-spring-boot-basics"
      -
        id: "82-cs-spring-boot-adv"
      -
        id: "actuator"
      -
        id: "spring-data-rest"
      -
        id: "scs"
        title: "Spring Cloud Services"
      -
        id: "scs-labs-setup"
      -
        id: "config"
      -
        id: "service-discovery"
      -
        id: "circuit-breakers"
      -
        id: "datamicroservices"
        title: "Data Microservices"
      -
        id: "springcloud-dataflow"
